### PR TITLE
[IMPROVEMENT] remove unused member "path" from FILE_INFO structure

### PR DESCRIPTION
**Pull request by fvalasiad**

### CODE REVIEW

**Comment by zvr** [comment]
!?!

Why remove it? We had it there for a reason.
Isn't it always used when recording files, calling https://github.com/eellak/gsoc2022--build-recorder/blob/d8d787e084cc2780e45d7624e658cfa0148b1c88/src/record.c#L156 ?

**Comment by fvalasiad** [comment]
@zvr Yes indeed, fact is though that 'record_file' is only ever called inside 'handle_open'. 'path' is never used again and I don't see any reason we should ever store it.

**Comment by fvalasiad** [comment]
**We are still recording `path` with `record_file(3)`, we just don't store it, run the tests with this branch and see for yourself!**

**Comment by zvr** [comment]
But what is to gain? Saving a few bytes?

It would be better to keep the info (and potentially add more, like file size), so that we are free to decouple the logging steps. Especially if we are going to be considering multi-threads.

**Comment by fvalasiad** [comment]
@zvr Well yes, a couple of mega bytes worth of RAM for "big builds". One could argue though that less state means less problems! Especially in multi-threaded code where said state is going to be shared.

Fair point though, but shouldn't we at least notify future contributors that said fields are for debug using comments here and there?

**Comment by fvalasiad** [comment]
Closing this pull request since we decided not to merge.

**Pull request closed without merging**
