### PR TITLE
Include guards

### PR DESCRIPTION
**Pull request by fvalasiad**

### CODE REVIEW

**Comment by zvr** [comment]
Why are these needed?

**Comment by fvalasiad** [comment]
@zvr No apparent reason at the moment, just precautions for the future. Is there any reason not to add 'em?

**Comment by zvr** [comment]
These are not general-purpose header files that will be included by different `.c` files and might be included more than once... No need to guard for this.

**Comment by fvalasiad** [comment]
Okay i guess.

**Pull request closed without merging**
